# @diegotorres50: import routes from a controller directory
love_phrases_app:
    resource: "@LovePhrasesAppBundle/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
